language: go

go:
- stable

os:
- linux
- windows
- osx

env:
  - GO111MODULE=on

matrix:
  allow_failures:
  - os: windows
    go: master
  fast_finish: true

before_install:
- go get -u golang.org/x/tools/cmd/goimports
- go get -u golang.org/x/lint/golint
- chmod +x travis_build.sh

install:
- go get -t -v ./...

notifications:
  email: false

script:
- go test -v -race ./...
- go vet ./...
- goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")
- golint $(go list ./... | grep -v /vendor/)
- "./travis_build.sh"

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $travisCIToken
  file:
  - ethr_kai_linux.zip
  - ethr_kai_windows.zip
  - ethr_kai_osx.zip
  on:
    repo: karminski/ethr-kai
    branch: master
    tags: true

